### ISSUE TITLE
not run on Node 4.0

### ISSUE THREAD

**Issue by aokihu** [guo-yu/player#41]
Node 4.0 is not run

**Comment by bttf** [comment]
+1

Seems to be lame and speaker packages. Lame worked for me once I upgraded but speaker is breaking on latest

**Comment by llaine** [comment]
+1

**Comment by Jermorin** [comment]
+1

**Comment by BeneStem** [comment]
please fix this!

**Comment by dandrewrichardson** [comment]
+1
