### ISSUE TITLE
node 4 support not released to npm

### ISSUE THREAD

**Issue by BeneStem** [guo-yu/player#43]
thank you so much for the node 4 support fix. could you please release it to npm. the latest version is still 0.5.0 which has no node 4 support :(

**Comment by Jermorin** [comment]
+1

**Comment by llaine** [comment]
+1

**Comment by dandrewrichardson** [comment]
+1

**Comment by John-Lin** [comment]
+1

**Comment by guo-yu** [comment]
`v0.5.1` has been shipped :)

**Comment by BeneStem** [comment]
Thank you so much, great job!
