### ISSUE TITLE
Warning output

### ISSUE THREAD

**Issue by llaine** [guo-yu/player#58]
I'm getting this output when the player module is included in my script.

`2015-12-18 16:42:22.628 node[1539:46341] 16:42:22.627 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.`

The script 

```javascript

import Player from 'player';

var player = new Player(/* url.mp3 */);
```

npm version : 3.4.1
node version : 5.0.0

**Comment by guo-yu** [comment]
This might be a error throwed by a core-audio  API on Mac OS X, `player` module depends on `node-speaker` to interact with native speaker.

**Comment by llaine** [comment]
You right, thank you.
